address: "localhost:8080"

db-driver: "postgres"
db-protocol: "postgresql"
db-host: "sentinel-db"
db-port: "5432"
db-name: "sentinel_db"
db-ssl-mode: "disable"

redis-host: "sentinel-redis"
redis-port: "6379"

token-access-duration: "15m"
token-refresh-duration: "2h"

oauth2flow-state-duration: "1h"