version: "3.9"
services:
  postgres:
    image: postgres:14.3-alpine
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=qwerty
      - POSTGRES_DB=sentinel_db
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD", "pg_isready", "-q", "-U", "root", "-d", "sentinel_db" ]
      interval: 5s
      timeout: 5s
      retries: 5

  postgres_migration:
    image: migrate/migrate
    volumes:
      - ./pkg/db/migration:/migration
    command: [
      "-path", "/migration", "-database",
      "postgresql://root:qwerty@postgres:5432/sentinel_db?sslmode=disable",
      "up"
    ]
    depends_on:
      postgres:
        condition: service_healthy

  redis:
    image: redis
    command: >
      --requirepass qwerty
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DB_DRIVER=postgres
      - DB_PROTOCOL=postgresql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=root
      - DB_PASSWORD=qwerty
      - DB_NAME=sentinel_db
      - DB_SSL_MODE=disable
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=qwerty
      - GIN_MODE=debug
    depends_on:
      redis:
        condition: service_healthy
      postgres:
        condition: service_healthy
      postgres_migration:
        condition: service_started