// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"encoding/json"
	"time"

	"github.com/google/uuid"
)

type Guild struct {
	ID             int64  `json:"id"`
	DiscordID      int64  `json:"discord_id"`
	OwnerDiscordID int64  `json:"owner_discord_id"`
	Name           string `json:"name"`
	Icon           string `json:"icon"`
}

type GuildConfig struct {
	ID        int64           `json:"id"`
	Json      json.RawMessage `json:"json"`
	CreatedAt time.Time       `json:"created_at"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	DiscordID    int64     `json:"discord_id"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreatedAt    time.Time `json:"created_at"`
}

type User struct {
	ID            int64  `json:"id"`
	DiscordID     int64  `json:"discord_id"`
	Username      string `json:"username"`
	Discriminator string `json:"discriminator"`
	Verified      bool   `json:"verified"`
	Email         string `json:"email"`
	Avatar        string `json:"avatar"`
	Banner        string `json:"banner"`
	// color encoded as an integer representation of hexadecimal color code
	AccentColor int64     `json:"accent_color"`
	CreatedAt   time.Time `json:"created_at"`
}

type UserGuild struct {
	AccountDiscordID int64 `json:"account_discord_id"`
	GuildDiscordID   int64 `json:"guild_discord_id"`
	Permissions      int64 `json:"permissions"`
}
