// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"encoding/json"
	"time"
)

type Guild struct {
	ID             int64  `json:"id"`
	DiscordID      string `json:"discord_id"`
	OwnerDiscordID string `json:"owner_discord_id"`
	Name           string `json:"name"`
	Icon           string `json:"icon"`
}

type GuildConfig struct {
	ID        int64           `json:"id"`
	Json      json.RawMessage `json:"json"`
	CreatedAt time.Time       `json:"created_at"`
}

type User struct {
	ID            int64  `json:"id"`
	DiscordID     string `json:"discord_id"`
	Username      string `json:"username"`
	Discriminator string `json:"discriminator"`
	Verified      bool   `json:"verified"`
	Email         string `json:"email"`
	Avatar        string `json:"avatar"`
	Banner        string `json:"banner"`
	// color encoded as an integer representation of hexadecimal color code
	AccentColor int64     `json:"accent_color"`
	CreatedAt   time.Time `json:"created_at"`
}

type UserGuild struct {
	AccountDiscordID string `json:"account_discord_id"`
	GuildDiscordID   string `json:"guild_discord_id"`
	Permissions      int64  `json:"permissions"`
}
