// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
)

type Querier interface {
	CreateOrUpdateGuild(ctx context.Context, arg CreateOrUpdateGuildParams) (Guild, error)
	CreateOrUpdateGuildConfig(ctx context.Context, arg CreateOrUpdateGuildConfigParams) (GuildConfig, error)
	CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error)
	CreateOrUpdateUserGuildRel(ctx context.Context, arg CreateOrUpdateUserGuildRelParams) (UserGuild, error)
	CreateUserGuildRel(ctx context.Context, arg CreateUserGuildRelParams) (UserGuild, error)
	DeleteGuild(ctx context.Context, discordID string) error
	DeleteGuildConfig(ctx context.Context, discordID string) error
	DeleteUser(ctx context.Context, discordID string) error
	DeleteUserGuildRel(ctx context.Context, arg DeleteUserGuildRelParams) error
	GetGuild(ctx context.Context, discordID string) (GetGuildRow, error)
	GetGuildConfig(ctx context.Context, discordID string) (GuildConfig, error)
	GetUser(ctx context.Context, discordID string) (User, error)
	GetUserGuild(ctx context.Context, arg GetUserGuildParams) (GetUserGuildRow, error)
	GetUserGuildRel(ctx context.Context, arg GetUserGuildRelParams) (UserGuild, error)
	GetUserGuilds(ctx context.Context, accountDiscordID string) ([]GetUserGuildsRow, error)
	TryCreateGuildConfig(ctx context.Context, arg TryCreateGuildConfigParams) (GuildConfig, error)
	UpdateGuildConfig(ctx context.Context, arg UpdateGuildConfigParams) error
}

var _ Querier = (*Queries)(nil)
