// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateOrUpdateGuild(ctx context.Context, arg CreateOrUpdateGuildParams) (Guild, error)
	CreateOrUpdateGuildConfig(ctx context.Context, arg CreateOrUpdateGuildConfigParams) (GuildConfig, error)
	CreateOrUpdateUser(ctx context.Context, arg CreateOrUpdateUserParams) (User, error)
	CreateOrUpdateUserGuildRel(ctx context.Context, arg CreateOrUpdateUserGuildRelParams) (UserGuild, error)
	CreateSession(ctx context.Context, arg CreateSessionParams) (Session, error)
	CreateUserGuildRel(ctx context.Context, arg CreateUserGuildRelParams) (UserGuild, error)
	DeleteGuild(ctx context.Context, discordID int64) error
	DeleteGuildConfig(ctx context.Context, discordID int64) error
	DeleteUser(ctx context.Context, discordID int64) error
	DeleteUserGuildRel(ctx context.Context, arg DeleteUserGuildRelParams) error
	GetGuild(ctx context.Context, discordID int64) (Guild, error)
	GetGuildConfig(ctx context.Context, discordID int64) (GuildConfig, error)
	GetSession(ctx context.Context, id uuid.UUID) (Session, error)
	GetUser(ctx context.Context, discordID int64) (User, error)
	GetUserGuildRel(ctx context.Context, arg GetUserGuildRelParams) (UserGuild, error)
	GetUserGuilds(ctx context.Context, accountDiscordID int64) ([]GetUserGuildsRow, error)
	TryCreateGuildConfig(ctx context.Context, arg TryCreateGuildConfigParams) (GuildConfig, error)
	UpdateGuildConfig(ctx context.Context, arg UpdateGuildConfigParams) error
}

var _ Querier = (*Queries)(nil)
