DROP TABLE IF EXISTS "user" CASCADE;

DROP TABLE IF EXISTS "guild" CASCADE;

DROP TABLE IF EXISTS "user_guild" CASCADE;

DROP TABLE IF EXISTS "guild_config" CASCADE;

DROP TABLE IF EXISTS "session" CASCADE;